### ISSUE TITLE
Improve mobile responsiveness

### ISSUE THREAD

**Issue by nathangobinet** [adrien-nf/git-report-web#42]
We need a toggle edit / preview in dashbnoard
and fix script top flex on main page

**Comment by adrien-nf** [comment]
But do we though? Would someone really use the mobile app for this? I feel we should just display the homepage with video, and instead of the script, we should just tell them to connect to to their computer, shouldn't we?

**Comment by nathangobinet** [comment]
Responsivness is not just about mobile usage, it also concern people with weird screen ratio (9:16 for example) or in a multi window mode

**Comment by nathangobinet** [comment]
a7e2efa4a7a1e828f078a492af540bb35f341eb0
